before_commands:
    - pip install -r termsandconditions_demo/requirements.txt
checks:
    python:
        code_rating: true
        duplicate_code: true
        variables_used_before_assignment: true
        variables_unused_wildcard_import: true
        variables_unused_import: true
        variables_unused_variable: true
        variables_unused_argument: true
        variables_unpacking_non_sequence: true
        variables_undefined_variable: true
        variables_undefined_loop_variable: true
        variables_undefined_all_variable: true
        variables_unbalanced_tuple_unpacking: true
        variables_redefined_outer_name: true
        variables_redefined_builtin: true
        variables_redefine_in_handler: true
        variables_no_name_in_module: true
        variables_invalid_all_object: true
        variables_global_variable_undefined: true
        variables_global_variable_not_assigned: true
        variables_global_statement: true
        variables_global_at_module_level: true
        typecheck_unexpected_keyword_arg: true
        typecheck_too_many_function_args: true
        typecheck_redundant_keyword_arg: true
        typecheck_not_callable: true
        typecheck_no_value_for_parameter: true
        typecheck_no_member: true
        typecheck_missing_kwoa: true
        typecheck_maybe_no_member: true
        typecheck_duplicate_keyword_arg: true
        typecheck_assignment_from_none: true
        typecheck_assignment_from_no_return: true
        string_truncated_format_string: true
        string_unused_format_string_key: true
        string_too_many_format_args: true
        string_too_few_format_args: true
        string_mixed_format_string: true
        string_missing_format_string_key: true
        string_format_needs_mapping: true
        string_constant_anomalous_unicode_escape_in_string: true
        string_constant_anomalous_backslash_in_string: true
        string_bad_str_strip_call: true
        string_bad_format_string_key: true
        string_bad_format_character: true
        open_mode_bad_open_mode: true
        newstyle_bad_super_call: true
        miscellaneous_fixme: true
        logging_unsupported_format: true
        logging_too_few_args: true
        logging_too_many_args: true
        imports_wildcard_import: true
        logging_format_truncated: true
        logging_not_lazy: true
        imports_deprecated_module: true
        imports_import_error: true
        imports_import_self: true
        imports_reimported: true
        imports_relative_import: true
        format_superfluous_parens: true
        format_trailing_whitespace: true
        format_unnecessary_semicolon: true
        imports_cyclic_import: true
        format_missing_final_newline: true
        format_mixed_indentation: true
        format_multiple_statements: true
        format_old_ne_operator: true
        format_backtick: true
        format_bad_indentation:
            indentation: tab
        format_bad_whitespace: true
        format_line_too_long:
            max_length: '80'
        format_lowercase_l_suffix: true
        exceptions_pointless_except: true
        exceptions_raising_bad_type: true
        exceptions_raising_non_exception: true
        exceptions_raising_string: true
        exceptions_bare_except: true
        exceptions_binary_op_exception: true
        exceptions_catching_non_exception: true
        exceptions_broad_except: true
        exceptions_notimplemented_raised: true
        classes_super_init_not_called: true
        classes_valid_slots: true
        design_abstract_class_little_used: true
        design_abstract_class_not_used: true
        design_interface_not_implemented: true
        exceptions_bad_except_order: true
        classes_no_method_argument: true
        classes_no_self_argument: true
        classes_no_self_use: true
        classes_non_iterator_returned: true
        classes_non_parent_init_called: true
        classes_signature_differs: true
        classes_protected_access: true
        classes_bad_context_manager: true
        classes_bad_mcs_classmethod_argument: true
        classes_bad_mcs_method_argument: true
        classes_bad_staticmethod_argument: true
        classes_interface_is_not_class: true
        classes_method_hidden: true
        classes_missing_interface_method: true
        classes_no_init: true
        basic_unreachable: true
        basic_useless_else_on_loop: true
        basic_yield_outside_function: true
        classes_abstract_method: true
        classes_access_member_before_definition: true
        classes_arguments_differ: true
        classes_attribute_defined_outside_init: true
        classes_bad_classmethod_argument: true
        basic_pointless_string_statement: true
        basic_return_arg_in_generator: true
        basic_return_in_init: true
        basic_return_outside_function: true
        basic_star_args: true
        basic_unnecessary_lambda: true
        basic_unnecessary_pass: true
        basic_missing_reversed_argument: true
        basic_nonexistent_operator: true
        basic_not_in_loop: true
        basic_old_raise_syntax: true
        basic_pointless_statement: true
        basic_invalid_name:
            functions: '[a-z_][a-z0-9_]{2,30}$'
            variables: '[a-z_][a-z0-9_]{2,30}$'
            whitelisted_names: 'i,j,k,ex,Run,_'
            constants: '(([A-Z_][A-Z0-9_]*)|(__.*__))$'
            attributes: '[a-z_][a-z0-9_]{2,30}$'
            arguments: '[a-z_][a-z0-9_]{2,30}$'
            class_attributes: '([A-Za-z_][A-Za-z0-9_]{2,30}|(__.*__))$'
            inline_vars: '[A-Za-z_][A-Za-z0-9_]*$'
            classes: '[A-Z_][a-zA-Z0-9]+$'
            modules: '(([a-z_][a-z0-9_]*)|([A-Z][a-zA-Z0-9]+))$'
            methods: '[a-z_][a-z0-9_]{2,30}$'
        basic_lost_exception: true
        basic_missing_docstring: true
        basic_missing_module_attribute: true
        basic_empty_docstring: true
        basic_eval_used: true
        basic_exec_used: true
        basic_expression_not_assigned: true
        basic_function_redefined: true
        basic_init_is_generator: true
        basic_abstract_class_instantiated: true
        basic_assert_on_tuple: true
        basic_bad_reversed_sequence: true
        basic_dangerous_default_value: true
        basic_duplicate_argument_name: true
        basic_duplicate_key: true
    javascript:
        wrap_regex: true
        wrap_iife: true
        vars_on_top: true
        valid_typeof: true
        valid_jsdoc: true
        use_isnan: true
        space_return_throw_case: true
        radix: true
        one_var: true
        no_wrap_func: true
        no_with: true
        no_void: true
        no_var: true
        no_use_before_define: true
        no_unused_vars: true
        no_unused_expressions: true
        no_unreachable: true
        no_underscore_dangle: true
        no_undefined: true
        no_undef_init: true
        no_undef: true
        no_trailing_spaces: true
        no_ternary: true
        no_sync: true
        no_sparse_arrays: true
        no_space_before_semi: true
        no_shadow_restricted_names: true
        no_shadow: true
        no_sequences: true
        no_self_compare: true
        no_script_url: true
        no_return_assign: true
        no_reserved_keys: true
        no_redeclare: true
        no_proto: true
        no_process_exit: true
        no_process_env: true
        no_plusplus: true
        no_path_concat: true
        no_octal_escape: true
        no_octal: true
        no_obj_calls: true
        no_new_wrappers: true
        no_new_require: true
        no_new_func: true
        no_new_object: true
        no_native_reassign: true
        no_negated_in_lhs: true
        no_nested_ternary: true
        no_loop_func: true
        no_mixed_spaces_and_tabs: true
        no_multi_str: true
        no_iterator: true
        no_label_var: true
        no_lone_blocks: true
        no_lonely_if: true
        no_labels: true
        no_func_assign: true
        no_inline_comments: true
        no_implied_eval: true
        no_inner_declarations: true
        no_invalid_regexp: true
        no_irregular_whitespace: true
        no_floating_decimal: true
        no_fallthrough: true
        no_extra_strict: true
        no_extra_semi: true
        no_extra_boolean_cast: true
        no_extra_bind: true
        no_extend_native: true
        no_ex_assign: true
        no_eval: true
        no_eq_null: true
        no_empty_label: true
        no_empty_class: true
        no_empty: true
        no_else_return: true
        no_dupe_keys: true
        no_div_regex: true
        no_delete_var: true
        no_debugger: true
        no_control_regex: true
        no_constant_condition: true
        no_console: true
        no_comma_dangle: true
        no_caller: true
        no_bitwise: true
        no_array_constructor: true
        no_alert: true
        new_parens: true
        new_cap: true
        guard_for_in: true
        func_names: true
        eqeqeq: true
        eol_last: true
        dot_notation: true
        default_case: true
        curly: true
        consistent_this: true
        consistent_return: true
        camelcase: true
        block_scoped_var: true

tools:
    pylint:
        python_version: 2
        config_file: 'devscripts/checkers/pylintrc'
filter:
    excluded_paths:
        - '*tests*'
        - '*/vendor/*'
        - '*/migrations/*'
build:
    dependencies:
        before:
            - pip install -r termsandconditions_demo/requirements.txt
    environment:
        python: '2.7.7'
