git:
  depth: 1
language: python
python:
- '2.7.11'
- '3.5.1'
cache: pip
env:
    matrix:
        - DJANGO="Django<1.9,>=1.8"
          - SETTINGS="settings_pre_1_10"
        - DJANGO="Django<1.10,>=1.9"
          - SETTINGS="settings"
        - DJANGO="Django<1.11,>=1.10"
          - SETTINGS="settings"
        - DJANGO="Django<1.12,>=1.11"
          - SETTINGS="settings"
install:
    - pip install $DJANGO
    - pip install -r termsandconditions_demo/requirements_ci.txt
script:
  coverage run --source=termsandconditions,termsandconditions_demo --rcfile=devscripts/checkers/coveragerc
  manage.py test --settings=$SETTINGS
sudo: false
after_success: coveralls
deploy:
  provider: pypi
  upload_docs: no
  user: Tim.White
  password:
    secure: e8H/IHRzcNpZUwohtgDt4srkWZu7Ofa8q5N/w3sg3ZyaL0vbzhQle9D1gn1PwAoiTJQHYfuYvhP0G9HM4aZ19OEbJ/gAPXNFd3bVXD/g8kI1rRA/VN/W4DEAp/53rNly8idH+6BO5OvwH0NlPUjhisv5yCV/FAPHENSpwmdTu5g=
  on:
    repo: cyface/django-termsandconditions
