language: python
python:
  - "2.7"
cache: pip
# command to install dependencies
install:
  - "pip install -r termsandconditions_demo/requirements_dev.txt"
# command to run tests
script: "python manage.py jenkins termsandconditions --coverage-rcfile=devscripts/checkers/coveragerc"
script: "coverage run --source=termsandconditions,termsandconditions_demo --rcfile=devscripts/checkers/coveragerc manage.py test"
sudo: false
after_success:
  coveralls