language: python
python:
  - "2.7"
cache: pip
# command to install dependencies
install:
  - "pip install -r termsandconditions_demo/requirements_dev.txt"
# command to run tests
script: "python manage.py jenkins termsandconditions --coverage-rcfile=devscripts/checkers/coveragerc"
sudo: false