git:
  depth: 1
language: python
python:
- 3.7
services:
- postgresql
cache: pip
env:
- DJANGO="Django<2.1,>=2.0" SETTINGS="termsandconditions_demo.settings"
- DJANGO="Django<2.1,>=2.0" SETTINGS="termsandconditions_demo.settings" TERMS_DATABASE="postgresql"
- DJANGO="Django<2.2,>=2.1" SETTINGS="termsandconditions_demo.settings"
- DJANGO="Django<2.2,>=2.1" SETTINGS="termsandconditions_demo.settings" TERMS_DATABASE="postgresql"
- DJANGO="Django<2.3,>=2.2" SETTINGS="termsandconditions_demo.settings"
- DJANGO="Django<2.3,>=2.2" SETTINGS="termsandconditions_demo.settings" TERMS_DATABASE="postgresql"
- DJANGO="Django<3.1,>=2.2" SETTINGS="termsandconditions_demo.settings"
- DJANGO="Django<3.1,>=2.2" SETTINGS="termsandconditions_demo.settings" TERMS_DATABASE="postgresql"

install:
- pip install $DJANGO
- pip install -r termsandconditions_demo/requirements_ci.txt
before_script:
- psql -c 'CREATE DATABASE termsandconditions;' -U postgres
- psql -c "CREATE USER termsandconditions WITH PASSWORD '';" -U postgres
- psql -c "ALTER USER termsandconditions CREATEDB;" -U postgres
script: coverage run --source=termsandconditions,termsandconditions_demo --rcfile=devscripts/checkers/coveragerc
  manage.py test --settings=$SETTINGS
sudo: false
after_success: coveralls
deploy:
  provider: pypi
  skip_existing: true
  upload_docs: false
  user: Tim.White
  password:
    secure: EnmVvUnhnNhCpWQBpU2BcwyBe3VM+BL3Ijrwfkubw89WjwXrMgDdvy+UIivkgBz5exgNoT2lGcsxIyAfvPimRVs8I018AMu3lNSPGmRUJAHMFi25kmtrI4m/XzMsR0TNv4KD9X5FAIW2noC0wMHpldzffVg24gZRMjrpAti6d3c=
  on:
    tags: true
    repo: cyface/django-termsandconditions
