language: python
python:
- '2.7.11'
- '3.5.1'
cache: pip
env:
    matrix:
        - DJANGO="Django<1.9,>=1.8"
        - DJANGO="Django<1.10,>=1.9"
install:
    - pip install $DJANGO
    - pip install -r termsandconditions_demo/requirements_ci.txt
script: coverage run --source=termsandconditions,termsandconditions_demo --rcfile=devscripts/checkers/coveragerc
  manage.py test
sudo: false
after_success: coveralls
deploy:
  provider: pypi
  upload_docs: no
  user: Tim.White
  password:
    secure: e8H/IHRzcNpZUwohtgDt4srkWZu7Ofa8q5N/w3sg3ZyaL0vbzhQle9D1gn1PwAoiTJQHYfuYvhP0G9HM4aZ19OEbJ/gAPXNFd3bVXD/g8kI1rRA/VN/W4DEAp/53rNly8idH+6BO5OvwH0NlPUjhisv5yCV/FAPHENSpwmdTu5g=
  on:
    repo: cyface/django-termsandconditions
